server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: haechang
    password: haechang1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 278439571060-cul6mlcb2r3a92tcv4rj7n8p8ej7rhnl.apps.googleusercontent.com
            client-secret: XSQ0cbhulRCgOUSaGTxDKCq3
            scope:
            - email
            - profile
            
          facebook:
            client-id: 359949025399801
            client-secret: f2537bb86e711789fc12b173271dc8de
            scope:
            - email
            - public_profile